In [1]:
import numpy as np

arr = np.random.randint(1,100,size=(10,5))

In [2]:
arr.shape

(10, 5)

In [8]:
b = arr.reshape(5,10)

b.shape
print(b.ndim)
b

2


array([[72, 83, 63, 97, 25, 61, 67, 77, 35, 50],
       [91, 80, 17, 81, 72, 35, 33, 77, 96, 86],
       [91, 12, 43, 36, 95, 97, 47, 93, 22, 61],
       [12,  4, 77, 28, 33, 50, 99, 11, 72, 78],
       [19, 23, 71, 61, 69, 72, 80, 60, 14,  3]])

In [12]:
flatten = b.flatten()
print(flatten.ndim)

flatten

column_wise_flattening = np.ravel(b, order='C')
print(column_wise_flattening.ndim)
column_wise_flattening


1
1


array([72, 83, 63, 97, 25, 61, 67, 77, 35, 50, 91, 80, 17, 81, 72, 35, 33,
       77, 96, 86, 91, 12, 43, 36, 95, 97, 47, 93, 22, 61, 12,  4, 77, 28,
       33, 50, 99, 11, 72, 78, 19, 23, 71, 61, 69, 72, 80, 60, 14,  3])

In [21]:
a = np.random.randint(1,10,size=(2,3))
b = np.random.randint(20,30,size=(2,3))

print(a)
print(b)   

[[8 4 5]
 [7 4 5]]
[[23 21 23]
 [25 25 29]]


### concatenate

In [ ]:
con_row = np.concatenate((a,b), axis=0)  # row wise concatenation
print(con_row)
con_col = np.concatenate((a,b), axis=1)  # column wise concatenation
print(con_col)

[[ 8  4  5]
 [ 7  4  5]
 [23 21 23]
 [25 25 29]]
[[ 8  4  5 23 21 23]
 [ 7  4  5 25 25 29]]


####  Ndarray Manipulation - 2

In [ ]:
# Transpose of a matrix
import numpy as np
mat = np.array([[10, 20, 30],
                [40, 50, 60]
         ])

transpose = mat.T
print(transpose)

[[10 40]
 [20 50]
 [30 60]]


In [30]:
# array split
a = np.random.randint(1,10,size=(10,))

splited_array = np.array_split(a, 3)
print(splited_array)

# splited_array = np.split(a, 3) # this will give an error because the array cannot be split into equal parts



[array([8, 3, 2, 3]), array([8, 6, 8]), array([5, 4, 7])]


## Ndarray Arithmetic Operators and Mathematical function

In [42]:
#faster for vectorized operations
import numpy as np

x = np.array([8, 20, 9, 40, 50])
y = np.array([1, 2, 3, 4, 5])

addition = x + y
print("Addition:", addition)

subtraction = x - y
print("Subtraction:", subtraction)

multiplication = x * y
print("Multiplication:", multiplication)

division = x / y
print("Division:", division)

remainder = x % y
print("Remainder:", remainder)

Addition: [ 9 22 12 44 55]
Subtraction: [ 7 18  6 36 45]
Multiplication: [  8  40  27 160 250]
Division: [ 8. 10.  3. 10. 10.]
Remainder: [0 0 0 0 0]


In [ ]:
# mathemitical functions

# trigonometric functions

#sin cos tan take radian values as input
sin_values = np.sin(x)
print("Sine values:", sin_values)

cos_values = np.cos(x)
print("Cosine values:", cos_values)

tan_values = np.tan(x)
print("Tangent values:", tan_values)

deg_conversion = np.rad2deg(x) #there are also deg2rad function to convert degree to radian
print("Degree to Radian conversion:", deg_conversion)

Sine values: [-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
Cosine values: [-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]
Tangent values: [ 0.64836083  2.23716094 -6.4053312  -1.11721493 -0.27190061]
Degree to Radian conversion: [ 572.95779513 1145.91559026 1718.87338539 2291.83118052 2864.78897565]


In [40]:
#log

base_10_log = np.log10(x)
print("Base 10 Logarithm:", base_10_log)

two_log = np.log2(x) #2 diye koto bar vag kora jabe
print("Base 2 Logarithm:", two_log)

Base 10 Logarithm: [0.90308999 1.30103    1.47712125 1.60205999 1.69897   ]
Base 2 Logarithm: [3.         4.32192809 4.9068906  5.32192809 5.64385619]


In [43]:
# square root
sqrt_values = np.sqrt(x)
print("Square Root:", sqrt_values)

Square Root: [2.82842712 4.47213595 3.         6.32455532 7.07106781]


In [45]:
sum = np.sum(x)
print("Sum of elements in x:", sum)

cumalitive_sum = np.cumsum(x)
print("Cumulative Sum:", cumalitive_sum)

Sum of elements in x: 127
Cumulative Sum: [  8  28  37  77 127]
