In [1]:
import numpy as np

arr = np.random.randint(1,100,size=(10,5))

In [2]:
arr.shape

(10, 5)

In [8]:
b = arr.reshape(5,10)

b.shape
print(b.ndim)
b

2


array([[72, 83, 63, 97, 25, 61, 67, 77, 35, 50],
       [91, 80, 17, 81, 72, 35, 33, 77, 96, 86],
       [91, 12, 43, 36, 95, 97, 47, 93, 22, 61],
       [12,  4, 77, 28, 33, 50, 99, 11, 72, 78],
       [19, 23, 71, 61, 69, 72, 80, 60, 14,  3]])

In [12]:
flatten = b.flatten()
print(flatten.ndim)

flatten

column_wise_flattening = np.ravel(b, order='C')
print(column_wise_flattening.ndim)
column_wise_flattening


1
1


array([72, 83, 63, 97, 25, 61, 67, 77, 35, 50, 91, 80, 17, 81, 72, 35, 33,
       77, 96, 86, 91, 12, 43, 36, 95, 97, 47, 93, 22, 61, 12,  4, 77, 28,
       33, 50, 99, 11, 72, 78, 19, 23, 71, 61, 69, 72, 80, 60, 14,  3])

In [21]:
a = np.random.randint(1,10,size=(2,3))
b = np.random.randint(20,30,size=(2,3))

print(a)
print(b)   

[[8 4 5]
 [7 4 5]]
[[23 21 23]
 [25 25 29]]


### concatenate

In [ ]:
con_row = np.concatenate((a,b), axis=0)  # row wise concatenation
print(con_row)
con_col = np.concatenate((a,b), axis=1)  # column wise concatenation
print(con_col)

[[ 8  4  5]
 [ 7  4  5]
 [23 21 23]
 [25 25 29]]
[[ 8  4  5 23 21 23]
 [ 7  4  5 25 25 29]]
