In [1]:
import numpy as np

arr = np.random.randint(1,100,size=(10,5))

In [2]:
arr.shape

(10, 5)

In [8]:
b = arr.reshape(5,10)

b.shape
print(b.ndim)
b

2


array([[72, 83, 63, 97, 25, 61, 67, 77, 35, 50],
       [91, 80, 17, 81, 72, 35, 33, 77, 96, 86],
       [91, 12, 43, 36, 95, 97, 47, 93, 22, 61],
       [12,  4, 77, 28, 33, 50, 99, 11, 72, 78],
       [19, 23, 71, 61, 69, 72, 80, 60, 14,  3]])

In [12]:
flatten = b.flatten()
print(flatten.ndim)

flatten

column_wise_flattening = np.ravel(b, order='C')
print(column_wise_flattening.ndim)
column_wise_flattening


1
1


array([72, 83, 63, 97, 25, 61, 67, 77, 35, 50, 91, 80, 17, 81, 72, 35, 33,
       77, 96, 86, 91, 12, 43, 36, 95, 97, 47, 93, 22, 61, 12,  4, 77, 28,
       33, 50, 99, 11, 72, 78, 19, 23, 71, 61, 69, 72, 80, 60, 14,  3])

In [21]:
a = np.random.randint(1,10,size=(2,3))
b = np.random.randint(20,30,size=(2,3))

print(a)
print(b)   

[[8 4 5]
 [7 4 5]]
[[23 21 23]
 [25 25 29]]


### concatenate

In [ ]:
con_row = np.concatenate((a,b), axis=0)  # row wise concatenation
print(con_row)
con_col = np.concatenate((a,b), axis=1)  # column wise concatenation
print(con_col)

[[ 8  4  5]
 [ 7  4  5]
 [23 21 23]
 [25 25 29]]
[[ 8  4  5 23 21 23]
 [ 7  4  5 25 25 29]]


####  Ndarray Manipulation - 2

In [ ]:
# Transpose of a matrix
import numpy as np
mat = np.array([[10, 20, 30],
                [40, 50, 60]
         ])

transpose = mat.T
print(transpose)

[[10 40]
 [20 50]
 [30 60]]


In [30]:
# array split
a = np.random.randint(1,10,size=(10,))

splited_array = np.array_split(a, 3)
print(splited_array)

# splited_array = np.split(a, 3) # this will give an error because the array cannot be split into equal parts



[array([8, 3, 2, 3]), array([8, 6, 8]), array([5, 4, 7])]


## Ndarray Arithmetic Operators and Mathematical function

In [42]:
#faster for vectorized operations
import numpy as np

x = np.array([8, 20, 9, 40, 50])
y = np.array([1, 2, 3, 4, 5])

addition = x + y
print("Addition:", addition)

subtraction = x - y
print("Subtraction:", subtraction)

multiplication = x * y
print("Multiplication:", multiplication)

division = x / y
print("Division:", division)

remainder = x % y
print("Remainder:", remainder)

Addition: [ 9 22 12 44 55]
Subtraction: [ 7 18  6 36 45]
Multiplication: [  8  40  27 160 250]
Division: [ 8. 10.  3. 10. 10.]
Remainder: [0 0 0 0 0]


In [ ]:
# mathemitical functions

# trigonometric functions

#sin cos tan take radian values as input
sin_values = np.sin(x)
print("Sine values:", sin_values)

cos_values = np.cos(x)
print("Cosine values:", cos_values)

tan_values = np.tan(x)
print("Tangent values:", tan_values)

deg_conversion = np.rad2deg(x) #there are also deg2rad function to convert degree to radian
print("Degree to Radian conversion:", deg_conversion)

Sine values: [-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
Cosine values: [-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]
Tangent values: [ 0.64836083  2.23716094 -6.4053312  -1.11721493 -0.27190061]
Degree to Radian conversion: [ 572.95779513 1145.91559026 1718.87338539 2291.83118052 2864.78897565]


In [40]:
#log

base_10_log = np.log10(x)
print("Base 10 Logarithm:", base_10_log)

two_log = np.log2(x) #2 diye koto bar vag kora jabe
print("Base 2 Logarithm:", two_log)

Base 10 Logarithm: [0.90308999 1.30103    1.47712125 1.60205999 1.69897   ]
Base 2 Logarithm: [3.         4.32192809 4.9068906  5.32192809 5.64385619]


In [43]:
# square root
sqrt_values = np.sqrt(x)
print("Square Root:", sqrt_values)

Square Root: [2.82842712 4.47213595 3.         6.32455532 7.07106781]


In [45]:
sum = np.sum(x)
print("Sum of elements in x:", sum)

cumalitive_sum = np.cumsum(x)
print("Cumulative Sum:", cumalitive_sum)

Sum of elements in x: 127
Cumulative Sum: [  8  28  37  77 127]


### Numpy Logical Functions

In [48]:
#comparison
x = np.array([8, 20, 9, 40, 50])
y = np.array([1, 2, 3, 40, 5])

greater_than = x > y
print("Comparison (x > y):", greater_than)

equal = x == y
print("Comparison (x == y):", equal)    
# all shows if all elements are true
print("All elements in x are greater than y:", np.all(greater_than))
# any shows if any element is true
print("Any element in x is greater than y:", np.any(greater_than))

Comparison (x > y): [ True  True  True False  True]
Comparison (x == y): [False False False  True False]
All elements in x are greater than y: False
Any element in x is greater than y: True


### ndarray Sorting


In [ ]:
# inplace sorting
arr = np.array([5, 2, 9, 1, 5, 6])
copy = arr.copy() # this will create a copy of the array
copy.sort() # this will sort the array in place
print("Sorted array:", copy)
print("Original array:", arr) # original array remains unchanged


Sorted array: [1 2 5 5 6 9]
Original array: [5 2 9 1 5 6]


In [51]:
# copy sorting
print("Original array:", arr)
sorted_arr = np.sort(arr) # this will return a sorted copy of the array
print("Sorted array:", sorted_arr)
print("Original array:", arr) # original array remains unchanged

Original array: [5 2 9 1 5 6]
Sorted array: [1 2 5 5 6 9]
Original array: [5 2 9 1 5 6]


In [54]:
#2D array sorting
arr_2d = np.array([[3, 2, 1],
                   [6, 5, 4]])
hor_sorted = np.sort(arr_2d, axis=1) # sort each row
print("Sorted 2D array (row-wise):\n", hor_sorted)
ver_sorted = np.sort(arr_2d, axis=0) # sort each column
print("Sorted 2D array (column-wise):\n", ver_sorted)

Sorted 2D array (row-wise):
 [[1 2 3]
 [4 5 6]]
Sorted 2D array (column-wise):
 [[3 2 1]
 [6 5 4]]


### ndarray Searching

In [58]:
# np.where
x = np.array([5, 2, 9, 1, 15, 6])

index = np.where(x == 10)
print("Indices of elements equal to 10:", index)

index = np.where(x > 10)
print("Indices of elements greater than 10:", index)

index = np.where(x % 2 == 0)
print("Indices of even elements in x:", index)
index = np.where(x < 8, x, 0) # this will return the elements of x that are less than 8, and 0 for the rest
print("Elements of x less than 8 (else 0):", index)

Indices of elements equal to 10: (array([], dtype=int64),)
Indices of elements greater than 10: (array([4]),)
Indices of even elements in x: (array([1, 5]),)
Elements of x less than 8 (else 0): [5 2 0 1 0 6]


In [60]:
mat = np.array([[10, 20, 30],
                [40, 50, 60]
         ])

index = np.where(mat > 25)
print(index)

(array([0, 1, 1, 1]), array([2, 0, 1, 2]))


In [64]:
maximum_values = np.argmax(mat) # this will return the indices of the maximum values along the specified axis
print("Indices of maximum values along columns:", maximum_values)

minimum_values = np.argmin(mat) # this will return the indices of the minimum values along the specified axis
print("Indices of minimum values along columns:", minimum_values)  

Indices of maximum values along columns: 5
Indices of minimum values along columns: 0


### Ndarray counting

In [25]:
import numpy as np
a = np.random.randint(1 ,100 ,size=(100,))
print(a)

[19 52 26 42 44 77 18 23 23 19 67 36 78 20 88  8 88  1 72 48 53 16 64 84
 43 74 30 10 48 64 69 49 94 86 28 19  1 29 87 50 22 63 44 75 60 22 24 58
 91 64 99 85  3 91 54 56 52 27  8 82 60 21 35 42 15 72 76 26 85 15 70 53
 62 30 34 43 54 67 32 18  7 66 87 78 60 24 86 23 39 23 86 81 76 36  2 67
 47 51 77 74]


In [21]:
value_greater_than_60 = np.count_nonzero(a > 60)
print(value_greater_than_60)

44


In [29]:
unique_values = np.unique(a,return_counts=True) # this will return the unique values and their counts
print("Unique values:", unique_values[0])
print("Counts:", unique_values[1])

Unique values: [ 1  2  3  7  8 10 15 16 18 19 20 21 22 23 24 26 27 28 29 30 32 34 35 36
 39 42 43 44 47 48 49 50 51 52 53 54 56 58 60 62 63 64 66 67 69 70 72 74
 75 76 77 78 81 82 84 85 86 87 88 91 94 99]
Counts: [2 1 1 1 2 1 2 1 2 3 1 1 2 4 2 2 1 1 1 2 1 1 1 2 1 2 2 2 1 2 1 1 1 2 2 2 1
 1 3 1 1 3 1 3 1 1 2 2 1 2 2 2 1 1 1 2 3 2 2 2 1 1]


### Statistical function

In [ ]:
#Data load
import numpy as np
data = np.genfromtxt('student_scores.csv', delimiter=',', skip_header=1)

print(data)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [43]:
math_scores = data[::, :1] # this will select the first column (math scores)
print(math_scores.T)

max_math_score = np.max(math_scores)
print("Maximum math score:", max_math_score)
min_math_score = np.min(math_scores)
print("Minimum math score:", min_math_score)
average_math_score = np.mean(math_scores)
print("Average math score:", average_math_score) 
median_math_score = np.median(math_scores)
print("Median math score:", median_math_score)
standard_deviation_math_score = np.std(math_scores) 
print("Standard Deviation of math scores:", standard_deviation_math_score)

[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
Maximum math score: 95.0
Minimum math score: 45.0
Average math score: 73.15
Median math score: 73.5
Standard Deviation of math scores: 13.788672887555204


In [39]:
english_scores = data[::, 1:2] # this will select the second column (english scores)
print(english_scores.T)

[[85. 67. 92. 52. 75. 90. 60. 57. 89. 70. 69. 82. 64. 78. 93. 71. 79. 86.
  63. 97.]]


In [38]:
english_scores = data[::, 2:3] # this will select the third column (english scores)
print(english_scores.T)

[[82. 72. 88. 58. 80. 91. 62. 54. 87. 76. 68. 81. 60. 74. 90. 69. 78. 85.
  65. 96.]]


### Linear Algebra with NumPy

In [50]:
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              ])
B = np.array([[7, 8, 9],
              [10, 11, 12],
              [23, 24, 25]
              ])
               
dot_product = np.dot(A, B) # this will calculate the dot product of A and B
print("Dot product of A and B:\n", dot_product)

#trace of a matrix is the sum of the elements on the main diagonal
trace_B = np.trace(B)
print("Trace of B:", trace_B)

#Determinant of a matrix
determinant_B = np.linalg.det(B)
print("Determinant of B:", determinant_B)

#rank of a matrix
rank_B = np.linalg.matrix_rank(B)
print("Rank of B:", rank_B)

Dot product of A and B:
 [[ 96 102 108]
 [216 231 246]]
Trace of B: 43
Determinant of B: -7.781215285633702e-15
Rank of B: 2
