In [1]:
import numpy as np

arr1 = np.array([1,2,3])

arr1 = arr1 * 5

print(arr1)

[ 5 10 15]


In [2]:
# Ndarray

import numpy as np

# 1d array

arr1 = np.array([1,2,3,4,5])

print(type(arr1))

# 2d array
arr2 = np.array([[1,2,3], #row 1
                 [4,5,6]]) #row 2


#3d array
arr3 = np.array([
                [ [1,2,3],
                  [4,5,6] ],
                
                [ [1,2,3],
                  [4,5,6] ]
                 
                 ])


<class 'numpy.ndarray'>


In [3]:
#array attributes

# dimentions
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

#data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

#size
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
(5,)
(2, 3)
(2, 2, 3)
int64
int64
int64
5
6
12


## Ndarray Data type ##

In [4]:
import numpy as np

arr = np.array([1,2,3])
print(arr.dtype)

arr = np.array([1.3,3.5,3.4])
print(arr.dtype)

arr = np.array([1,2,3.3])
print(arr.dtype) #upcasting 

arr = np.array([1,2,'B'])
print(arr.dtype) #upcasting to string

int64
float64
float64
<U21


selecting a data type for an array

In [5]:
arr = np.array([1,2,4])
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr.dtype)

int64
int16


## Ndarray creation from existing data

In [6]:
#list
import numpy as np
lst = [10,20,30,40,50.6]

arr = np.array(lst, dtype=np.int32)

print(arr)
print(type(arr))
print(arr.dtype)

mixed_lst = [10,True,'hello', 3.14 ]

arr = np.array(mixed_lst)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

matrix = [[1,2,3],
          [4,5,6],
          [7,8,9]]
arr = np.array(matrix)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)



[10 20 30 40 50]
<class 'numpy.ndarray'>
int32
['10' 'True' 'hello' '3.14']
<class 'numpy.ndarray'>
<U32
(4,)
1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(3, 3)
2


In [12]:
#Tuples 
import numpy as np
tup = (10,20,30,40,50.6)

arr = np.array(tup)  
arr = arr.astype(np.int16) 

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)


[10 20 30 40 50]
<class 'numpy.ndarray'>
int16
(5,)
1


In [14]:
#Sets 
import numpy as np
st = {10,20,30,40,50.6}

# arr = np.array(st,dtype=np.int32)
# print(arr.dtype)  
arr = arr.astype(np.int16) 

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)


[10 20 30 40 50]
<class 'numpy.ndarray'>
int16
(5,)
1


In [19]:
#Dictionaries
import numpy as np
dct = {'a':10, 'b':20, 'c':30}

keys = dct.keys()
values = dct.values()
print(keys)
print(values)
items = dct.items()
print(items)

# keys to ndarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
# arr = arr.astype(np.int16)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

dict_keys(['a', 'b', 'c'])
dict_values([10, 20, 30])
dict_items([('a', 10), ('b', 20), ('c', 30)])
['a' 'b' 'c']
<class 'numpy.ndarray'>
['a' 'b' 'c']
<U1
(3,)
1


Array Creation with random values

In [62]:
import numpy as np

arr = np.random.uniform(50, 100,(3,3,4))

print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[[78.58515644 79.65313608 97.55377504 79.7935172 ]
  [98.29094148 50.15653361 65.22770816 84.92034194]
  [51.08337752 92.76907051 72.36985509 97.30765386]]

 [[82.97692536 92.90680603 84.74797597 63.1674169 ]
  [58.14185536 87.44229851 75.44423899 54.59233559]
  [53.49789565 62.95975384 67.96593196 77.36521233]]

 [[88.61158218 76.1586946  94.47819503 62.31549634]
  [90.6921668  50.95742489 66.43149058 72.63021302]
  [92.95552122 83.98014332 98.73184244 51.07420037]]]
float64
(3, 3, 4)
3


## array creation from range

In [66]:
import numpy as np

arr = np.arange(1,10,1)
mat = arr.reshape(3,3)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(mat)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int64
(9,)
1
9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [74]:
# linerarly spaced array
import numpy as np
arr = np.linspace(1,10,5)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[ 1.    3.25  5.5   7.75 10.  ]
<class 'numpy.ndarray'>
float64
(5,)
1
5


In [ ]:
# logspace
import numpy as np
arr = np.logspace(1,4,5,base=2) # x^1 to x^4 normally base is 10 but we can change it to 2 or etc
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[ 2.          3.36358566  5.65685425  9.51365692 16.        ]
<class 'numpy.ndarray'>
float64
(5,)
1


# indexing and slicing

In [81]:
# indexing
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])  # prints the first element
print(arr[-1])  # prints the last element

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2[0, 0])  # prints the first element of the first row
print(arr2[1, 2])  # prints the third element of the second row
print(arr2[2, 1])  # prints the second element of the third row

1
5
1
6
8


In [82]:
# slicing
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])  # prints elements from index 1 to 3
print(arr[:3])   # prints the first three elements
print(arr[2:])   # prints elements from index 2 to the end 
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2[0:2, 1:3])  # prints a subarray  

[2 3 4]
[1 2 3]
[3 4 5]
[[2 3]
 [5 6]]


### Ndarray Copy Advance Indexing and Iteration

In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

arr1_mod = arr1[1:4].copy() 
# arr1[1] = 20 

arr1_mod[0] = 20
print(arr1_mod) 
print(arr1)  


[20  3  4]
[1 2 3 4 5]


In [93]:
#Avanced Indexing
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

values = arr[[1, 3]]
print(values)  # prints [20, 40]

values2 = arr2[[0, 2], [1, 2]]
print(values2)  # prints [2, 9]

# boolean indexing
print(arr)
mask = arr > 25
print(mask)  # prints [False, False, True, True, True]
filtered_arr = arr[mask]
print(filtered_arr)  # prints [30, 40, 50]
 

[20 40]
[2 9]
[10 20 30 40 50]
[False False  True  True  True]
[30 40 50]


In [96]:
# iteration
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  
for i in arr:
    print(i)  # prints each row of the array
for i in np.nditer(arr):
    print(i)  # prints each element of the array

[1 2 3]
[4 5 6]
[7 8 9]
1
2
3
4
5
6
7
8
9


In [97]:
arr = np.array([1,2,3])
print(arr.ndim)

1
