In [1]:
import numpy as np

arr1 = np.array([1,2,3])

arr1 = arr1 * 5

print(arr1)

[ 5 10 15]


In [2]:
# Ndarray

import numpy as np

# 1d array

arr1 = np.array([1,2,3,4,5])

print(type(arr1))

# 2d array
arr2 = np.array([[1,2,3], #row 1
                 [4,5,6]]) #row 2


#3d array
arr3 = np.array([
                [ [1,2,3],
                  [4,5,6] ],
                
                [ [1,2,3],
                  [4,5,6] ]
                 
                 ])


<class 'numpy.ndarray'>


In [3]:
#array attributes

# dimentions
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

#data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

#size
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
(5,)
(2, 3)
(2, 2, 3)
int64
int64
int64
5
6
12


## Ndarray Data type ##

In [4]:
import numpy as np

arr = np.array([1,2,3])
print(arr.dtype)

arr = np.array([1.3,3.5,3.4])
print(arr.dtype)

arr = np.array([1,2,3.3])
print(arr.dtype) #upcasting 

arr = np.array([1,2,'B'])
print(arr.dtype) #upcasting to string

int64
float64
float64
<U21


selecting a data type for an array

In [5]:
arr = np.array([1,2,4])
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr.dtype)

int64
int16


## Ndarray creation from existing data

In [6]:
#list
import numpy as np
lst = [10,20,30,40,50.6]

arr = np.array(lst, dtype=np.int32)

print(arr)
print(type(arr))
print(arr.dtype)

mixed_lst = [10,True,'hello', 3.14 ]

arr = np.array(mixed_lst)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

matrix = [[1,2,3],
          [4,5,6],
          [7,8,9]]
arr = np.array(matrix)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)



[10 20 30 40 50]
<class 'numpy.ndarray'>
int32
['10' 'True' 'hello' '3.14']
<class 'numpy.ndarray'>
<U32
(4,)
1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(3, 3)
2


In [12]:
#Tuples 
import numpy as np
tup = (10,20,30,40,50.6)

arr = np.array(tup)  
arr = arr.astype(np.int16) 

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)


[10 20 30 40 50]
<class 'numpy.ndarray'>
int16
(5,)
1


In [14]:
#Sets 
import numpy as np
st = {10,20,30,40,50.6}

# arr = np.array(st,dtype=np.int32)
# print(arr.dtype)  
arr = arr.astype(np.int16) 

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)


[10 20 30 40 50]
<class 'numpy.ndarray'>
int16
(5,)
1


In [19]:
#Dictionaries
import numpy as np
dct = {'a':10, 'b':20, 'c':30}

keys = dct.keys()
values = dct.values()
print(keys)
print(values)
items = dct.items()
print(items)

# keys to ndarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
# arr = arr.astype(np.int16)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

dict_keys(['a', 'b', 'c'])
dict_values([10, 20, 30])
dict_items([('a', 10), ('b', 20), ('c', 30)])
['a' 'b' 'c']
<class 'numpy.ndarray'>
['a' 'b' 'c']
<U1
(3,)
1
